apiVersion: apps/v1
kind: Deployment
metadata:
  name: note
  labels:
    app: note
spec:
  replicas: 1
  template:
    metadata:
      name: note
      labels:
        app: note
    spec:
      containers:
        - name: note
          image: sooemma/note:20250616
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          volumeMounts:
            - mountPath: /root/conf
              name: note-config
      volumes:
        - name: note-config
          configMap:
            name: note-config
      restartPolicy: Always
  selector:
    matchLabels:
      app: note
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: note-config
data:
  application.yml: |-
    note:
      serverPort: 8080
      keylength: 6
      type: 1
      mysqlUrl: mysql.com:3306
      mysqlUsername: root
      mysqlPassword: 123456
      mysqlDatabasename: notes
      timezone: Asia/Shanghai
      redisUrl: 10.0.8.2:6379
      redisPassword: sxwtz
      redisDatabaseNum: 1
---
apiVersion: v1
kind: Service
metadata:
  name: note
spec:
  selector:
    app: note
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  