note:
  serverPort: 8080
  keylength: 6
  type: 1
  #type 0启用mysql 1启动redis
  mysqlUrl: mysql.com:3306
  mysqlUsername: root
  mysqlPassword: 123456
  mysqlDatabasename: notes
  timezone: Asia/Shanghai
  redisUrl: 192.168.8.8:6379
  redisPassword: xayf
  redisDatabaseNum: 1







