name: Go
# 名字
on:
  push:
    ## 在什么时候出发
    branches: [ main ]
    ## 出发的分支
  pull_request:
    branches: [ main ]

jobs:
  ## 具体触发的任务
  job1:
    runs-on: ubuntu-latest
    #container: golang:1.17-alpine
    # 指定容器运行
    steps:
      - uses: actions/checkout@v2
      - run: echo hello
      - run: echo hello2
      - name: Set up Go env
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build
        run: go build -v -o ./
